### PR TITLE
Adding L'atelier d'Arnoz boards

### PR DESCRIPTION
**Pull request by arnoz26**
- Adding RigMaster as ext 4
- Adding KLShield as ext5
- Adding Mollusk Expansion Board as exp3

### CODE REVIEW

**Review by mjrgh — CHANGES_REQUESTED** [review]
Here are some changes I'd suggest:

- Throughout pins.js, change the capitalization on the variables to match the Javascript convention of lower-first.  E.g., **var KLShieldOutPortAlias** should be **var klShieldOutPortAlias**.  I'd make the changes myself, but there are enough cross-references that it'd be better if you could do it so you can do some careful testing to make sure they're all right.
- Likewise the CSS selectors - e.g., **KLShieldBoardPinSelector** -> **klShieldBoardPinSelector**.  I'd like to keep these somewhat consistent.
- In pins.js function buildPinToHeaderMap(), you have a couple of board adder lines with **copies: 0**. Those won't do anything, because of the copies: 0, so you should just delete those; it's confusing to have the no-op code there.  (And if the code actually did do anything, it would be a confusing muddle, in that it references the "lite" boards.  I was going to ask what that was about, but the "copies: 0" makes me think it's just copy-and-paste cruft that can be deleted.)
- What's the purpose of css selector class="RigMasterBoardHide"?  I'm not sure what you're doing there.  If you want to disable power boards and chime boards for RigMaster, I think a better approach would be to not show the expansion board details section in the first place - instead, show a separate RigMaster details section that has the appropriate details for your boards.
- Based on the earlier email you sent, it sounds like you do intend to include Mollusk boards as an add-on option for the Pinscape Expansion Boards, which would explain why you added it to the expansion boards detail section. But on further reflection, I don't think we want to do that after all.  Mollusk boards are not going to integrate cleanly into an expansion board configuration that includes power boards, because there's no way to specify the relative ordering of power boards and Mollusk boards in the TLC5940 daisy chain. I think it's probably better to exclude Mollusk boards from the expansion board configuration options (and exclude power boards from your type 4 and 5 configuration options, for the same reason).  Advanced users who want to use a mixed configuration will still be able to do that, by pretending that a Power Board is two Mollusk boards (in an Expansion Board setup) or that a Mollusk Board is half a power board (in a RigMaster or KLShield setup).  I think advanced users and n00bs alike will be better served with that limitation than with creating the false impression that the Config Tool can properly figure the port layout for a mixed configuration, when it can't. If you want to think about how to modify the Config Tool to properly support a mixed configuration, go for it, but I think that's going to be a lot of work for not a lot of gain, since I expect very few people (if anyone at all) will attempt the mix-and-match.
- With the above in mind, we get back to my original thinking that we didn't need to add the "ext3" byte after all.  If power boards and Mollusk boards are mutually exclusive, it would be better to say that "ext1" means "number of Mollusk boards" in a type 4/5 configuration. I'm not sure it's worth making that change now, but I do think it would be cleaner, since it would make it more explicit that the two are mutually exclusive.
- I see that you're disabling most of the plunger sensor types for RigMaster. I just wanted to make sure that's actually necessary - is that because you've used all of the GPIO pins for other purposes?

**Comment by arnoz26** [comment]
Hi

Thanks for the answer !

- Done, and also done with RigMaster -> rigMaster & Mollusk -> mollusk
- Done the same 
- Done
- class="RigMasterBoardHide" is here to hide Number of MOSFET power boards & chime board selector when using RigMaster or KLShield. In my mind, I want Mollusk board to be use like an exp board, with kl25 pin assignment selector and all that stuff, but I don't don't want Mollusk to be used wit Pinscape exp board, AIO & lite. The same way I don't want MOSFET power boards & chime boards to be used with RigMaster & KLShield. For me it was the easiest way to do ( it's the same thing that in next point), but I don't know how to proceed to show my selector with kl25 pin assignment  like the way you want.... It's possible to use Mollusk with MOSFET power & chime boards, but I don't want it for "basic" users, only for "pro", then they will use stand alone mode for that....
- see above
- I don't know how to proceed for that, that's why I've used the ext3 option
- Yes, RigMaster only work with 10K pot...

I'll upload change soon

EDIT : I've made some change with class="RigMasterBoardHide" . I've created 2 class : 

- "molluskinput" to show/hide Mollusk
- "pinscapeexpboardinput" to show/hide officials Pinscape exp boards

I've also 2 new classes for RigMaster & KLShield : rigMasterBoardText & klShieldBoardText

**Comment by arnoz26** [comment]
😥

**Comment by mjrgh** [comment]
Hi - I finally had a chance to merge the PR.  I had to do a little reworking, so I did the work on my main branch instead of merging the PR directly.  I changed enough that it would probably be good if you could do some testing to make sure that the functionality for your boards is still working the way you want it to.  I did a little light testing to make sure nothing obvious is wrong, but hopefully you can take a closer look and test it more thoroughly.  Just update to the latest commit on the main branch and build to test it out.

Note that I reassigned "Number of Mollusk boards" to expansionBoards.ext1 in the saved configuration.  I think this is the correct way to assign the config slots given that Mollusk is mutually exclusive with Power Boards.  You can't have Power Boards in a KLShield or RigMaster system, and you can't have Mollusk boards in a Pinscape Expansion Board or Oak Micros system, so the two types are mutually exclusive and thus shouldn't be included at all in each other's configurations.  Since "Number of Power Boards" isn't a relevant thing to store when in a type 4/5 configuration, ext1 can (and should be) be repurposed for something that is relevant, namely the Mollusk board count.

Let me know how testing goes - if it looks like it's working, it's ready to go for an official release on my end.

**Comment by arnoz26** [comment]
Thanks a lot !!!
I've just check, and all work great.
Thanks translating my little English ;)
Just 3 last things :
- configure.htm Line 1744 : please replace Potentio**n**meter with Potentiometer
- Pin.js line 1650 : please replace "0xE9" with "0xEA"
- Pin.js line 1651 : please replace "0xEA" with "0xE9" 
- Pin.js line 1650 : please replace "0xE9" with "0xEA"
- Pin.js line 1650 : please replace "0xEA" with "0xE9"

**Comment by mjrgh** [comment]
Done - the changes have been merged into commit 42a70f4.  I posted a release build on mjrnet.org - 20211222 build.

**Pull request closed without merging**
