### PR TITLE
Updates for Pinscape AIO

### PR DESCRIPTION
**Pull request by MikePinball**
There are a lot of changes here that fall into 3 areas:
1. 4 new PNG files (with aio in the name)
2. Changes in the base code (some to better accommodate a new mode)
- Added text for "expert mode" - you can remove this if you want
- Is prvHardwareType used anywhere?
- Changed name of <div> expBoardAlt to expBoardText (to separate text from functionality)
- Eliminated hardcoding of expGpioPortAlias and expOutPortAlias in buildBoardPinButtons()
3. Additions for new mode 2 to support Pinscape AIO board in pins.js, Configure.htm, and OutputTester.htm including definition of 73 output ports on AIO board. In many places data or code with "main" is copied over, modified, and renamed to "aio"

Most things seem to work including the page popups for output or input Pin selection. One problem is that the pin highlighting is not working for the Pinscape AIO pages. I think it is something to do with "aioBoard_headers" not being seen properly. Perhaps you could look into this and help identify the problem. Once this works I will have to go in and edit the positions of the pins. Note also because of the "right-angle" header placement around the perimeter of the AIO, the 24 inputs will need to be split into 8+16 and the 32 power outputs will need to be split into 16+16. All of my headers are single row.

Obviously you can experiment quite a bit with the UI without actually needing a Pinscape AIO board to be present.

### CODE REVIEW

**Comment by MikePinball** [comment]
One other minor issue I have noticed. The image "KL25Z-pin-legend" does not quite draw in the right place for the Pinscape AIO boards. I'm not sure how to correct this.

**Comment by mjrgh** [comment]
It'd be great if you want to go back and nail down the various issues you pointed out - I'd rather hold off on merging until then.  I don't have any guesses off-hand about the pin highlighting.  The pin legend alignment (like most things) is handled through the CSS, so there's probably some little tweak you need there for your new class.

**Comment by MikePinball** [comment]
Thank you for the pointer to the CSS file - I should have realized that. That helped fix the problems with both the pin highlighting and the legend alignment.

**Comment by MikePinball** [comment]
The various problems noted above have been fixed as well as some other issues. I have tested this code and everything looks ok. This code is now ready for review, integration, and regression testing.

**Comment by MikePinball** [comment]
Can you please send me an updated PinscapeConfigTool.exe that contains the code to invoke the new OutputTester.htm so I can better verify things. I'm also thinking about a private version that allows me to turn on complete banks of outputs to speed testing of the Pinscape AIO. Right now I have to do each port individually. A "all on/all off" facility allows a quick test before so doing some individual tests as well.

**Comment by mjrgh** [comment]
A couple of notes for future reference, to make merging easier:

1. If you can set your editor to tab size = 4, that'll make the indenting look right when you view it, and it'll make the indenting come out right in added text.  Better still would be to just tell your editor not to use tabs when inserting or updating text, since tabs are **always** a pain for merging.  No one can ever agree on what a tab is and we're not going to start now.

2. Whenever you add a PNG file or other resource to the HTML folder, you need to add it to the Visual Studio project as well, so that it gets copied into the build.  In Visual Studio:

    - Right-click on the **html** folder under the **PinscapeConfigTool** project
    - Select Add > Existing Item
    - In the file selector, navigate to the file(s) in the html folder, select them, and click the **Add** button
    - For each added file, select it in the project tree view, and in the Properties pane, set **Copy to Output Directory** to **Copy if newer**

**Comment by MikePinball** [comment]
Thank you for doing the merge. A quick comparison shows you took all of the functional changes. I noticed one minor bug you fixed where I had "expBoardText" instead of "aioBoardText".

Yes sorry about the tabs. I know this problem and totally understand. Tabs will get you every time.

I added the bitmaps to build the binary but I forgot to add "PinscapeConfigTool.csproj" to the pull request.

**Pull request merged**
